version: '3'

services:
  web:
    container_name: ${APP_NAME}-web
    build:
      context: ./etc/docker/web
      args:
        APP_ENV: ${APP_ENV}
        SET_REAL_IP_FROM: ${SET_REAL_IP_FROM}
        SERVER_NAME: ${SERVER_NAME}
    ports:
      - ${WEB_EXTERNAL_PORT}:80
    env_file: .env
    links:
      - app
    volumes:
      - .:/var/www/html
      - storage:/var/www/html/storage
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: ./etc/docker/app/Dockerfile
      args:
        APP_ENV: $APP_ENV
    volumes:
      - .:/var/www/html
      - storage:/var/www/html/storage
    env_file: .env
#    links:
#      - db
# db:
#   container_name: ${APP_NAME}-db
#   image: mysql:5.7
#   ports:
#     - ${DB_EXTERNAL_PORT}:3306
#   command: [
#     '--character-set-server=utf8mb4',
#     '--collation-server=utf8mb4_unicode_ci',
#     '--skip-character-set-client-handshake'
#   ]
#   volumes:
#     - database:/var/lib/mysql
#   env_file: .env
# redis:
#   container_name: ${APP_NAME}-redis
#   image: redis

volumes:
  storage:
    driver: 'local'
# database:
